#!/usr/bin/python3

import sys
import os

if len(sys.argv) < 2:
   print("Usage: ./retrieve-pi-data <collection-type>")

collection_type = sys.argv[1]

callgraph_files = ["callgraphs/sample", "logs/sample"]
strace_files = ["straces/sample", "logs/sample"]

to_retrieve = []
if collection_type == "callgraph_analysis":
   to_retrieve = callgraph_files
elif collection_type == "resource_analysis":
   to_retrieve = strace_files

for f in to_retrieve:
   os.system("rsync -rzcv pi@ceres.cs.princeton.edu:~/"+collection_type+"/"+f+" "+collection_type+"/"+f)

os.system("rsync -rzcv pi@ceres.cs.princeton.edu:~/"+collection_type+"/no-pip-libs.txt "+collection_type)
